name: robot-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - gymnasium-robotics
    - gym-aloha
    - wandb
    - ipython
    - numpy
    - matplotlib
    - gym-aloha
    - wandb
    - ipython
    - numpy
    - matplotlib